# CRM Services Package
from .tag import (
    get_tag,
    list_tags,
    create_tag,
    update_tag,
    delete_tag,
    add_tags_to_customer,
    add_tags_to_lead,
    remove_tag_from_customer,
    remove_tag_from_lead,
    get_tag_statistics,
)
from .customer import (
    get_customer,
    list_customers,
    create_customer,
    update_customer,
    delete_customer,
)
from .customer_360 import get_customer_360
from .lead import (
    get_lead,
    list_leads,
    create_lead,
    update_lead,
    delete_lead,
    create_lead_from_conversation,
    auto_generate_leads_for_conversations,
    check_duplicate_lead,
    check_duplicate_lead_for_customer,
    get_leads_by_customer,
    calculate_intent_score,
    HIGH_INTENT_THRESHOLD,
    MEDIUM_INTENT_THRESHOLD,
    INTENT_SCORE_MIN,
    INTENT_SCORE_MAX,
    INTENT_BASE_SCORE,
    INTENT_SCORE_WEIGHTS,
    VALID_STATUS_TRANSITIONS,
)
from .lifecycle import (
    get_lifecycle_stages,
    get_lifecycle_stage,
    create_lifecycle_stage,
    update_lifecycle_stage,
    delete_lifecycle_stage,
    get_lifecycle_stage_logs,
    transition_lifecycle_stage,
    get_funnel_stats,
    init_default_stages,
)
from .auto import (
    apply_auto_transitions,
    match_stage_for_signals,
    build_signals,
    stage_config_rules,
    DefaultConversationActivityProvider,
    ConversationActivityProvider,
)

__all__ = [
    # Tag services
    "get_tag",
    "list_tags",
    "create_tag",
    "update_tag",
    "delete_tag",
    "add_tags_to_customer",
    "add_tags_to_lead",
    "remove_tag_from_customer",
    "remove_tag_from_lead",
    "get_tag_statistics",
    # Customer services
    "get_customer",
    "list_customers",
    "create_customer",
    "update_customer",
    "delete_customer",
    # Customer 360
    "get_customer_360",
    # Lead services
    "get_lead",
    "list_leads",
    "create_lead",
    "update_lead",
    "delete_lead",
    "create_lead_from_conversation",
    "auto_generate_leads_for_conversations",
    "check_duplicate_lead",
    "check_duplicate_lead_for_customer",
    "get_leads_by_customer",
    "calculate_intent_score",
    "HIGH_INTENT_THRESHOLD",
    "MEDIUM_INTENT_THRESHOLD",
    "INTENT_SCORE_MIN",
    "INTENT_SCORE_MAX",
    "INTENT_BASE_SCORE",
    "INTENT_SCORE_WEIGHTS",
    "VALID_STATUS_TRANSITIONS",
    # Lifecycle services
    "get_lifecycle_stages",
    "get_lifecycle_stage",
    "create_lifecycle_stage",
    "update_lifecycle_stage",
    "delete_lifecycle_stage",
    "get_lifecycle_stage_logs",
    "transition_lifecycle_stage",
    "get_funnel_stats",
    "init_default_stages",
    # Auto-transition rule engine
    "apply_auto_transitions",
    "match_stage_for_signals",
    "build_signals",
    "stage_config_rules",
    "DefaultConversationActivityProvider",
    "ConversationActivityProvider",
]
